### ISSUE TITLE
chore: build an environment

### ISSUE THREAD

**Issue by shinGangan** [shinGangan/create-nuxt-app-for-monopepo#1]
## Context

環境構築。

## TODO

- [ ] chore: Nuxt
- [ ] chore: Storybook
- [ ] chore: Vitest + test-utils
- [ ] chore: Nuxt I18n
- [ ] chore: Nuxt SEO
- [ ] chore: Nuxt Robots
- [ ] chore: ESLint, Prettier
- [ ] chore: Renovate bot
- [ ] chore: GitHub Workflows
